/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;

import java.sql.Date;
import java.sql.Time;

import ca.mcgill.ecse.flexibook.model.FlexiBook;
import ca.mcgill.ecse.flexibook.model.User;



public class FlexiBookApplication {
	private static FlexiBook flexiBook;
	private static User currentUser;
	
	
    public static FlexiBook getFlexiBook() {
    	if(flexiBook== null) {
    		flexiBook = new FlexiBook();
    	}
        return flexiBook;
    }

    public static void main(String[] args) {
        //System.out.println(new FlexiBookApplication().getGreeting());
    }

	public static User getCurrentUser() {
		return currentUser;
	
	}
	public static User setCurrentUser(User user) {
		currentUser = user;
		return currentUser;
	}
	
	private static Date systemDate = null;
	private static Time systemTime = null;
	
	public static Date getSystemDate() {
		return systemDate;
	}
	
	public static Time getSystemTime() {
		return systemTime;
	}
	
	public static void setSystemDate(Date date) {
		systemDate = date;
	}
	
	public static void setSystemTime(Time time) {
		systemTime = time;
	}
}
