/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;

import ca.mcgill.ecse.flexibook.model.FlexiBook;



public class FlexiBookApplication {
	
    public static FlexiBook getFlexiBook() {
        return null;
    }

    public static void main(String[] args) {
        //System.out.println(new FlexiBookApplication().getGreeting());
    }
}
