/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;

import ca.mcgill.ecse.flexibook.model.FlexiBook;

public class FlexiBookApplication {
    public String getGreeting() {
        return "Hello world.";
    }
    
 
    	 
private static FlexiBook flexiBook;

private static FlexiBook getFlexiBook() {

  if (flexiBook == null) {
	  flexiBook = new FlexiBook();
  }

 return flexiBook;

 }

    	

    public static void main(String[] args) {
        System.out.println(new FlexiBookApplication().getGreeting());
    }

}